package org.aueb.representation;

import io.quarkus.test.junit.QuarkusTest;
import jakarta.inject.Inject;
import org.aueb.domain.RegistrationRequest;
import org.aueb.domain.User;
import org.aueb.util.enumerations.ActivityStatus;
import org.aueb.util.enumerations.UserType;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.lang.reflect.Field;
import java.util.Date;
import java.util.List;

@QuarkusTest
public class RegistrationRequestMapperTest {

    @Inject
    RegistrationRequestMapper mapper;

    @Test
    public void toRepresentationTest() {
        // 1. Δημιουργία του User Entity
        User user = new User(
                "visitor1",
                "secret123",
                "Giannis",
                "Papadopoulos",
                "giannis@aueb.gr",
                UserType.Visitor
        );

        // Ορισμός του userId μέσω Reflection (καθώς δεν υπάρχει public setter στον User)
        setUserIdViaReflection(user, 101);

        // 2. Δημιουργία του Request Entity
        RegistrationRequest request = new RegistrationRequest();
        Date now = new Date();
        request.setRequestDate(now);

        // Κλήση της μεθόδου setUser που υπάρχει στο RegistrationRequest (Business Method)
        request.setUser(user);

        // Προσομοίωση έγκρισης από Admin
        User admin = new User("admin", "adminpass", "Admin", "User", "admin@test.com", UserType.Administrator);
        request.setApprovedStatus(true, admin);
        request.setStatus(ActivityStatus.Active);

        // Ορισμός registrationId μέσω Reflection (καθώς είναι private/autogenerated)
        setRegistrationIdViaReflection(request, 55);

        // 3. Κλήση του Mapper
        RegistrationRequestRepresentation representation = mapper.toRepresentation(request);

        // 4. Επαλήθευση (Assertions)
        Assertions.assertNotNull(representation);
        Assertions.assertEquals(55, representation.id);
        Assertions.assertEquals(now, representation.requestDate);
        Assertions.assertTrue(representation.approved);
        Assertions.assertEquals(ActivityStatus.Active, representation.status);

        // Έλεγχος Nested User Mapping
        Assertions.assertNotNull(representation.user);
        Assertions.assertEquals(101, representation.user.id);
        Assertions.assertEquals("visitor1", representation.user.username);
        Assertions.assertEquals("Giannis", representation.user.firstName);
        Assertions.assertEquals(UserType.Visitor, representation.user.userType);
    }

    @Test
    public void toModelTest() {
        // 1. Δημιουργία του Representation (DTO)
        RegistrationRequestRepresentation representation = new RegistrationRequestRepresentation();
        representation.id = 999;
        representation.approved = true;   // Αυτό θα αγνοηθεί από τον Mapper
        representation.status = ActivityStatus.Inactive;

        // Δημιουργία Nested UserRepresentation
        UserRepresentation userRep = new UserRepresentation();
        userRep.id = 202;
        userRep.username = "newuser";
        userRep.firstName = "Maria";
        userRep.lastName = "Dimou";
        userRep.email = "maria@aueb.gr";
        userRep.userType = UserType.Employee;

        representation.user = userRep;

        // 2. Κλήση του Mapper
        RegistrationRequest request = mapper.toModel(representation);

        // 3. Επαλήθευση
        Assertions.assertNotNull(request);
        Assertions.assertEquals(0, request.getRegistrationId()); // Το ID αγνοείται
        // Το approved παραμένει false (default τιμή του entity),
        // καθώς ο mapper δεν επιτρέπεται να το αλλάξει χωρίς admin check.
        Assertions.assertFalse(request.isApproved());

        Assertions.assertEquals(ActivityStatus.Inactive, request.getStatus());
    }

    @Test
    public void toRepresentationListTest() {
        User u = new User("emp1", "pass", "Nikos", "K.", "n@test.gr", UserType.Employee);
        RegistrationRequest r1 = new RegistrationRequest();
        r1.setUser(u);

        List<RegistrationRequest> requests = List.of(r1);
        List<RegistrationRequestRepresentation> reps = mapper.toRepresentationList(requests);

        Assertions.assertEquals(1, reps.size());
        Assertions.assertEquals("emp1", reps.get(0).user.username);
    }

    // --- Helper Methods ---

    private void setUserIdViaReflection(User user, int id) {
        try {
            Field field = User.class.getDeclaredField("userId");
            field.setAccessible(true);
            field.setInt(user, id);
        } catch (Exception e) {
            throw new RuntimeException("Failed to set userId via reflection", e);
        }
    }

    private void setRegistrationIdViaReflection(RegistrationRequest request, int id) {
        try {
            Field field = RegistrationRequest.class.getDeclaredField("registrationId");
            field.setAccessible(true);
            field.setInt(request, id);
        } catch (Exception e) {
            throw new RuntimeException("Failed to set registrationId via reflection", e);
        }
    }
}